# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    get_set_method_normalizer:
            class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
            public: false
            tags:
                - { name: serializer.normalizer }
    app.jwt_token_authenticator:
            class: DataBundle\Service\JwtAuthenticator
            arguments: ['@doctrine.orm.entity_manager', '@lexik_jwt_authentication.encoder']
  
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

     
         
