<?php

namespace DataBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActiveContacts($status)
    {
        $qb = $this->createQueryBuilder('c');
        $expr = $qb->expr();

        $qb ->where($expr->neq('c.status',$status))
            ->setParameter('status', $status);

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findHisContact($email)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->where('c.email = :email')
            ->setParameter('email', $email)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
