<?php

namespace DataBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findMessages($u, $c, $u1, $c1)
    {
        $qb = $this->createQueryBuilder('m');

        $qb
            ->where('m.user = :u AND m.contact = :c OR m.user = :u1 AND m.contact = :c1')
            ->setParameter('u', $u)
            ->setParameter('c', $c)
            ->setParameter('u1', $u1)
            ->setParameter('c1', $c1)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
